/** Available variables for template subject/body. Keys are placeholders like {{client_name}}. */
export const TEMPLATE_VARIABLES: { key: string; label: string }[] = [
  { key: '{{client_name}}', label: 'Client Name' },
  { key: '{{client_email}}', label: 'Client Email' },
  { key: '{{client_phone}}', label: 'Client Phone' },
  { key: '{{company_name}}', label: 'Company Name' },
  { key: '{{org_name}}', label: 'Organization Name' },
  { key: '{{org_admin_name}}', label: 'Org Admin Name' },
  { key: '{{org_email}}', label: 'Organization Email' },
  { key: '{{org_phone}}', label: 'Organization Phone' },
  { key: '{{service_name}}', label: 'Service Name' },
  { key: '{{service_description}}', label: 'Service Description' },
  { key: '{{current_date}}', label: 'Current Date' },
  { key: '{{date}}', label: 'Date' },
  { key: '{{today}}', label: 'Today' },
  { key: '{{deadline_date}}', label: 'Deadline Date' },
  { key: '{{follow_up_date}}', label: 'Follow-up Date' },
  { key: '{{login_email}}', label: 'Login Email' },
  { key: '{{login_password}}', label: 'Login Password' },
  { key: '{{login_url}}', label: 'Login URL' },
  { key: '{{additional_notes}}', label: 'Additional Notes' },
  { key: '{{amount}}', label: 'Amount' },
  { key: '{{document_name}}', label: 'Document Name' },
];
